name: Admin Service CI Pipeline

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Run tests (safe even if missing)
      - name: Run tests
        run: npm test --if-present

      # 5. Build project (safe if missing)
      - name: Build project
        run: npm run build --if-present

      # 6. SonarCloud Analysis (SAST + Code Quality)
      
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=Dhanigasree_admin-service_719c3fcc-07b5-4588-94b7-7da93932ba5b
            -Dsonar.organization=dhanigasree
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    

      # 7. Snyk Security Scan (SCA)
      - name: Snyk Scan
        uses: snyk/actions/node@master
        continue-on-error: true
        with:
          command: test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # 8. Slack Notification (Success - non blocking)
      - name: Slack Success Notification
        if: success()
        continue-on-error: true
        uses: 8398a7/action-slack@v3
        with:
          status: success
          text: "✅ Admin Service CI Passed"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

      # 9. Slack Notification (Failure - non blocking)
      - name: Slack Failure Notification
        if: failure()
        continue-on-error: true
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          text: "❌ Admin Service CI Failed"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
