name: CI Pipeline (SonarCloud + Snyk)

on:
  push:
    branches:
      - "main"
      - "pipeline/*"
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:

  SonarCloud:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Build (optional safe)
      - name: Build project
        run: npm run build --if-present

      # 5. SonarCloud Analysis
      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=Dhanigasree_admin-service_719c3fcc-07b5-4588-94b7-7da93932ba5b
            -Dsonar.organization=Dhanigasree
            -Dsonar.sources=.

  Snyk:
    runs-on: ubuntu-latest
    needs: SonarCloud

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Authenticate Snyk
      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      # 5. Run Snyk test
      - name: Run Snyk test
        run: npx snyk test --all-projects
