name:  search  CI Pipeline

on:
  push:
    branches: [ "main", "ci-pipeline" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  security-build:
    runs-on: ubuntu-latest

    steps:
     
      - name: Checkout Code
        uses: actions/checkout@v4 
    
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: Sonar Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_HOST_URL: http://YOUR_SONARQUBE_URL:9000
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    
     
    
        with:
          args: >
            -Dsonar.projectKey=Dhanigasree_admin-service_719c3fcc-07b5-4588-94b7-7da93932ba5b
            -Dsonar.organization=dhanigasree

      # - name: Sonar Quality Gate
      #   uses: SonarSource/sonarqube-quality-gate-action@v1
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #   timeout-minutes: 5
      - name: Snyk Security Scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test --severity-threshold=high

  
